name: build, push and deploy docker image
on:
  push:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t password-strength-tester .
      - name: push image
        run: |
          docker login -u razrvfx -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push password-strength-tester
